services:
  fastapi:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_post_db
    ports:
      - "9000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
